docs: add docs for backup COS
tkestack/kstone pull request #42
Opened 2021-12-20 14:41 UTC by maudL1n

2021-12-20 23:35 UTC, tangcong requested changes
thanks. The picture url seems to have a problem and cannot be displayed. (two docs)
https://github.com/maudL1n/kstone/blob/docs/docs/backup/..%5Cimages%5Cimages_for_backup_cos%5Ckstone-associate.png

2021-12-21 05:00 UTC, neweyes commented on docs/backup/Backup guide for Tencent COS_zh.md
> +集群节点映射: etcd集群的内网还有外网地址, 如果不用刻意省略
刻意 -》 可以

2021-12-21 05:01 UTC, neweyes commented on docs/backup/Backup guide for Tencent COS_zh.md
> +  - MaxBackups 是你想要存放的etcd备份文件的最大数量
超过这个数量将会怎么样

2021-12-21 05:55 UTC, tangcong commented on docs/backup/Backup guide for Tencent COS_zh.md
> +  - MaxBackups 是你想要存放的etcd备份文件的最大数量
会自动清理

2021-12-21 10:56 UTC, tangcong approved these changes
good job. lgtm.

2021-12-21 10:56 UTC, merged